vim.opt.cmdheight = 2
vim.opt.background="dark"
vim.opt.colorcolumn = "80"
vim.o.filetype="on"
vim.opt.concealcursor = "nc"
vim.opt.confirm = true
vim.opt.cursorline = true
vim.opt.emoji = true
vim.opt.encoding = "utf8"
vim.opt.equalalways = true
vim.opt.ex = true
vim.opt.expandtab = true
vim.opt.helpheight = 20
vim.opt.hidden = true
vim.opt.ignorecase = true
vim.opt.laststatus = 2
vim.opt.matchtime = 2
vim.opt.mouse = "nv"
vim.opt.hlsearch = false
vim.opt.showmode = false
vim.opt.number = true
vim.opt.pyxversion = 3
vim.opt.relativenumber = true
vim.opt.scrolloff = 10
vim.opt.shiftwidth = 4
vim.opt.shortmess = table.concat(vim.opt.shortmess, "r")
vim.opt.showmatch = true
vim.opt.signcolumn = "yes"
vim.opt.smartcase = true
vim.opt.tabstop = 4
vim.opt.termguicolors = true
vim.opt.title = true
vim.opt.titlestring = "NeoVim"
vim.opt.wrap = true
vim.opt.completeopt = "noinsert,noselect,menuone"
